/**
 * Metro resolves an asset import to the numeric module handle that `require`-style asset APIs take.
 *
 * Declared here rather than relying on `expo-env.d.ts`: that file is generated by the Expo CLI and
 * is gitignored, so a clean checkout running `pnpm -r typecheck` would not have it.
 */
declare module '*.wav' {
  const asset: number;
  export default asset;
}
